export const Ripper = {
  items: [
    {
      _id: "692eaaa3cda530d43888c77c",
      createdAt: "2025-12-02T09:00:19.606Z",
      updatedAt: "2025-12-02T09:00:19.607Z",
      title: "Peperiksaan SPM Tahun 2025",
      image: "692eaa8ccda530d43888c762",
    imageHero: {
          "createdAt": "2025-12-02T08:59:56.807Z",
          "updatedAt": "2025-12-02T08:59:56.807Z",
          "alt": "Peperiksaan SPM Tahun 2025",
          "filename": "really taking the exam.png",
          "mimeType": "image/png",
          "filesize": 843734,
          "width": 894,
          "height": 600,
          "focalX": 50,
          "focalY": 50,
        
        },
      readTime: 15,
      articleDate: "2026-01-01T12:00:00.000Z",
      attachments: [],
      content: {
        root: {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Lorem ipsum dolor sit amet consectetur adipiscing elit lectus urna quis habitasse, mauris posuere lobortis habitant hendrerit pulvinar parturient faucibus arcu consequat rutrum, auctor magna interdum class curabitur libero donec vitae ultricies ad. Porttitor suscipit mi eu lectus volutpat integer porta nibh rhoncus convallis phasellus penatibus, ultrices eget purus sodales lacus malesuada molestie ullamcorper turpis maecenas fusce. Montes nunc aenean pretium interdum sagittis laoreet dictum platea nam ultrices, commodo tellus habitasse imperdiet neque hendrerit pharetra non accumsan donec, ad nostra volutpat venenatis parturient fusce dictumst semper fames.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "A per tellus eu integer neque sed orci nullam, curae ac conubia quis duis ante primis fames, phasellus in molestie rutrum facilisi magnis suscipit. Ad a velit pellentesque arcu platea nec euismod, eget commodo donec lectus per sociosqu facilisis interdum, potenti massa tincidunt cum sagittis enim. Suspendisse conubia senectus quis suscipit id dictumst, iaculis lectus turpis velit magna dapibus, cum eleifend mollis magnis malesuada. Auctor litora hac mollis faucibus id sapien porta etiam, montes habitant himenaeos nunc facilisis vivamus senectus erat cras, dignissim donec tortor est ut laoreet sagittis.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Tristique nisi rhoncus mus mauris suspendisse libero eget sagittis, dignissim nec vestibulum diam fringilla curae conubia ad et, nascetur dis congue malesuada senectus non cubilia. Aliquet dictumst fringilla curae arcu taciti integer per sociosqu nam, neque erat dapibus vivamus porta litora hac feugiat enim, aptent nec consequat class ac molestie iaculis nunc. At litora accumsan posuere diam mus vitae, class risus varius et felis aliquam turpis, natoque est arcu aliquet a. Ad aenean vestibulum justo congue turpis class platea pretium commodo, facilisi sociosqu imperdiet sed proin ante cras at, fermentum enim eget rhoncus viverra mattis sollicitudin gravida.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Aenean egestas in sed libero nascetur convallis sollicitudin dis pellentesque, rutrum faucibus ac fringilla congue eu elementum erat, sodales at ut maecenas cras purus venenatis conubia. A phasellus integer eu donec bibendum sagittis, tincidunt auctor dictumst penatibus porttitor leo, sapien euismod etiam aliquam ac. Phasellus nulla augue tristique ridiculus cubilia eleifend placerat, molestie quisque aenean eros congue accumsan vitae, per pretium torquent class urna arcu.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Neque sapien ultrices nisi aliquet aenean ullamcorper, lacus mi eu risus fringilla eros, tempor consequat accumsan dignissim sociosqu. Metus placerat rhoncus massa cubilia sociis dignissim natoque inceptos in eleifend pretium, sodales auctor gravida eget suscipit arcu lobortis hac tempus cras tellus tristique, proin posuere lectus erat velit luctus habitant volutpat fermentum convallis. Ante nec aenean bibendum eget semper suscipit parturient dignissim conubia dictum morbi, vel volutpat vestibulum penatibus tellus erat egestas nullam interdum placerat. Nisl fusce nam neque imperdiet dictum pretium fermentum lacinia, mollis suspendisse viverra habitant class platea velit.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Vestibulum quis vivamus fermentum conubia pellentesque cubilia ac donec a eros quisque fringilla, placerat habitant consequat enim ullamcorper sed tortor penatibus sollicitudin convallis. Fames rhoncus proin gravida eros nisl ullamcorper, diam elementum urna dapibus mollis mattis leo, mauris habitant a sollicitudin duis. Accumsan per facilisis class sociis eget eleifend ultrices urna ad vestibulum hendrerit conubia fringilla taciti, habitant sociosqu mauris magnis phasellus feugiat montes a magna ligula aptent lacinia dictumst.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Posuere nascetur vulputate euismod porttitor laoreet vestibulum sapien dictum torquent luctus diam, tellus bibendum phasellus non lectus conubia pulvinar per fermentum urna varius cursus, donec rhoncus nibh faucibus auctor natoque inceptos nisl suscipit augue. At cursus ridiculus congue laoreet scelerisque nulla condimentum, purus vel posuere penatibus mi blandit eget hac, cras euismod ultrices rhoncus egestas mus. Habitasse sociis aliquam imperdiet maecenas penatibus tristique euismod odio, elementum nunc cras lectus ultrices nisi natoque nullam quam, tempus enim per primis litora luctus eros. Ultricies potenti auctor nulla suscipit nisl quam eget lacus pharetra morbi, etiam iaculis risus in tincidunt ullamcorper litora ac vel.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Justo taciti facilisi nullam fringilla nostra ad lacinia, egestas enim aliquam tincidunt non curabitur, vulputate urna feugiat habitasse viverra hac. Suscipit interdum sagittis fusce odio pretium felis porta tortor, gravida nulla posuere nibh aenean class aptent leo, ultrices bibendum montes vitae erat sollicitudin ridiculus. Lacinia integer pulvinar proin ac porta porttitor facilisi blandit viverra senectus est, curae nullam leo eget lacus quam congue feugiat tempus condimentum, phasellus augue urna ligula egestas etiam nibh fames laoreet parturient. Tempor semper imperdiet sociis mollis auctor fusce faucibus mauris proin ornare, torquent curae tristique sagittis nec malesuada viverra class.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "root",
          version: 1,
        },
      },
      category: "6927a87651d22936d3955278",
      __v: 0,
    },
    {
      _id: "692ea8cd66db544aa4fe503b",
      createdAt: "2025-12-02T08:52:29.875Z",
      updatedAt: "2025-12-02T08:52:29.875Z",
      title: "Hari Kanak-Kanak Sedunia",
      image: "692ea80984d07b7ae6c97f43",
      readTime: 10,
      articleDate: "2025-12-15T12:00:00.000Z",
      attachments: [],
      content: {
        root: {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Lorem ipsum dolor sit amet consectetur adipiscing, elit arcu rutrum ullamcorper vulputate, accumsan luctus risus blandit nisi. Integer sodales sem quis aptent id ante tempus, pulvinar proin gravida nullam netus cras et habitasse, sapien fringilla ullamcorper pellentesque malesuada nam. Ridiculus diam mollis pharetra facilisis rutrum torquent hendrerit justo rhoncus aliquam, fusce iaculis feugiat nunc cum id a mi.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Et morbi natoque egestas enim ullamcorper semper sociosqu, vulputate tempor facilisis massa suscipit netus tristique, integer sem aliquam erat tincidunt quam. Mauris dignissim id mollis fames nulla tempor rutrum fermentum ac lacinia a, nec penatibus non luctus orci sapien hac tortor commodo turpis. Luctus auctor venenatis ut ultricies at tristique fringilla, dictum cum semper montes placerat duis velit commodo, ultrices est etiam nam vehicula tincidunt.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Class nulla mauris vulputate praesent justo pulvinar, quis libero porttitor morbi eget, vitae tempor tortor curae gravida. Placerat ullamcorper porta quam senectus interdum nibh blandit magnis, morbi urna donec velit netus iaculis volutpat cum tellus, eros vivamus tortor varius posuere augue mi. Tempor faucibus non iaculis ante libero velit ac tincidunt facilisi quam in, bibendum mattis blandit quis venenatis senectus sapien sollicitudin porttitor. Lacinia suscipit morbi sociosqu parturient tristique ridiculus habitasse accumsan nullam nibh, sem orci porttitor felis purus habitant dictum viverra.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Nostra ut faucibus lacinia eu dis, gravida turpis tempus sodales pharetra, accumsan ridiculus nascetur malesuada. Aptent tortor dapibus accumsan a imperdiet venenatis, mollis ultricies cum pellentesque interdum id, facilisi elementum volutpat suscipit pharetra. Quisque porttitor sed nisi nulla dapibus primis quam ad sem, ultricies gravida etiam parturient lacinia est at vestibulum blandit, suspendisse imperdiet montes taciti interdum nunc fermentum nullam.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Duis ad urna proin fusce maecenas sem mattis, quam tristique sodales accumsan convallis primis nec imperdiet, nam aliquam risus ante taciti himenaeos. Faucibus sagittis potenti lacinia quam nisl mollis cursus ornare senectus justo dapibus mus inceptos, turpis leo commodo vel per ac erat curabitur sollicitudin fames cum. Torquent et dictum a dignissim luctus inceptos ullamcorper purus vehicula, lectus lacus porta commodo posuere mollis nam fringilla hac felis, ante ut quisque molestie sollicitudin eleifend massa platea.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "root",
          version: 1,
        },
      },
      category: "6927a87651d22936d3955278",
      __v: 0,
    },
    {
      _id: "692ea92d3b48f8a7a03194c6",
      createdAt: "2025-12-02T08:54:05.056Z",
      updatedAt: "2025-12-02T08:54:05.057Z",
      title: "Hari Sukan Malaysia 2025",
      image: "692ea90866db544aa4fe5060",
      readTime: 4,
      articleDate: "2025-12-11T12:00:00.000Z",
      attachments: [],
      content: {
        root: {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Lorem ipsum dolor sit amet consectetur adipiscing elit tincidunt malesuada eget gravida, dis hendrerit quis varius ante ac mauris accumsan fringilla dapibus. Id ac purus magna class nisi turpis curae, integer in viverra cras pellentesque at aliquet, scelerisque massa ante ut lectus tempor. Turpis libero iaculis orci phasellus leo justo conubia nec, fusce fermentum varius praesent hendrerit bibendum ridiculus massa, tempus magnis cum risus rhoncus est vulputate.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Quam velit massa netus sapien sociosqu lacinia nam suscipit, curabitur viverra neque habitant fames orci sagittis, turpis nulla ornare primis vehicula dapibus accumsan. Fames congue justo platea facilisis aptent mattis velit felis urna at netus faucibus accumsan, vestibulum ullamcorper class nisi enim taciti viverra sodales dapibus ut porta id scelerisque curabitur, condimentum lectus maecenas sed interdum luctus diam donec lacus parturient rhoncus nostra. At sociosqu posuere elementum ac pulvinar vel montes, dis luctus ullamcorper fringilla habitant imperdiet dignissim euismod, massa fames semper himenaeos risus varius.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "root",
          version: 1,
        },
      },
      category: "6927a87651d22936d3955278",
      __v: 0,
    },
    {
      _id: "692eaa3b69ba5b928a4fd444",
      createdAt: "2025-12-02T08:58:35.984Z",
      updatedAt: "2025-12-02T08:58:35.984Z",
      title: "Hari Guru Malaysia 2025",
      image: "692eaa2769ba5b928a4fd42b",
      readTime: 2,
      articleDate: "2025-12-04T12:00:00.000Z",
      attachments: [],
      content: {
        root: {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Lorem ipsum dolor sit amet consectetur adipiscing elit tincidunt malesuada eget gravida, dis hendrerit quis varius ante ac mauris accumsan fringilla dapibus. Id ac purus magna class nisi turpis curae, integer in viverra cras pellentesque at aliquet, scelerisque massa ante ut lectus tempor. Turpis libero iaculis orci phasellus leo justo conubia nec, fusce fermentum varius praesent hendrerit bibendum ridiculus massa, tempus magnis cum risus rhoncus est vulputate.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Quam velit massa netus sapien sociosqu lacinia nam suscipit, curabitur viverra neque habitant fames orci sagittis, turpis nulla ornare primis vehicula dapibus accumsan. Fames congue justo platea facilisis aptent mattis velit felis urna at netus faucibus accumsan, vestibulum ullamcorper class nisi enim taciti viverra sodales dapibus ut porta id scelerisque curabitur, condimentum lectus maecenas sed interdum luctus diam donec lacus parturient rhoncus nostra. At sociosqu posuere elementum ac pulvinar vel montes, dis luctus ullamcorper fringilla habitant imperdiet dignissim euismod, massa fames semper himenaeos risus varius.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "root",
          version: 1,
        },
      },
      category: "6927a87651d22936d3955278",
      __v: 0,
    },
    {
      _id: "692eaa7269ba5b928a4fd47d",
      createdAt: "2025-12-02T08:59:30.076Z",
      updatedAt: "2025-12-02T08:59:30.076Z",
      title: "Hari Bapa Malaysia 2025",
      image: "692eaa5569ba5b928a4fd467",
      imageAlt: "xxxx",
      readTime: 20,
      articleDate: "2025-11-30T12:00:00.000Z",
      eventDate:"2025-11-30T12:00:00.000Z",
      attachments: [{ id: "692eaa5da1e39a147eccec62" }],
      content: {
        root: {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Lorem ipsum dolor sit amet consectetur adipiscing, elit posuere a turpis phasellus suspendisse himenaeos, volutpat nascetur vitae neque at. Aliquet lectus porta eros vehicula quis et congue nibh magnis nisi maecenas natoque, accumsan sagittis consequat non aliquam eu euismod nullam cubilia dignissim at sodales, inceptos senectus pulvinar dis sociis massa himenaeos convallis gravida hendrerit aenean. Pellentesque cum aliquam blandit venenatis senectus in est facilisi fames, malesuada lectus suscipit tempus dictum duis quisque libero, hac elementum urna primis congue sed orci vivamus. Eu euismod diam scelerisque feugiat rhoncus tempus ultrices vestibulum himenaeos, fames dapibus vulputate condimentum lacus integer commodo pulvinar.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Porttitor iaculis in placerat at lectus eget, integer risus orci ut dignissim, eros mattis ad diam penatibus. Porttitor consequat a netus faucibus aliquam orci platea, commodo interdum mi in cubilia purus gravida, donec nostra sagittis cras vestibulum bibendum, elementum maecenas neque pellentesque proin mattis. Primis ac praesent sodales leo metus posuere, mus condimentum laoreet bibendum gravida quam nascetur, ridiculus eleifend sagittis per sem.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Tellus luctus arcu imperdiet eget integer quisque dui blandit condimentum senectus tincidunt sagittis, nullam bibendum lobortis aliquam eleifend platea hac vehicula taciti nibh. Sem sed fames habitant eu mi integer suscipit, ridiculus rhoncus donec facilisis primis imperdiet justo, facilisi penatibus pellentesque placerat erat scelerisque. Dictum curae sed laoreet ad primis sociosqu etiam facilisi auctor, curabitur eleifend consequat iaculis arcu volutpat tellus mauris, elementum cursus vestibulum eu et nisl odio nec. Aptent conubia orci pulvinar potenti curae ultrices neque porta eros nostra, nam nec facilisi velit curabitur nunc venenatis lacinia dictumst, id netus ultricies cursus taciti et sociosqu rutrum praesent. Fusce mauris sodales netus morbi ornare at nibh suscipit, tellus fermentum purus massa inceptos parturient facilisis, justo convallis faucibus urna ullamcorper curabitur gravida.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Potenti morbi ad nascetur imperdiet dictum class nisl ultricies vehicula viverra fermentum vulputate, mollis condimentum luctus mi nisi laoreet orci habitasse lectus euismod commodo rhoncus, sodales mus tincidunt magna pharetra molestie quam aliquet fringilla eros tempor. Metus ultricies erat in tellus facilisi vehicula sollicitudin natoque per est nisi dapibus quisque aliquam sociosqu, eget nisl convallis ad integer nam sodales nec rhoncus nulla massa montes scelerisque lacus. Ultricies vel consequat quisque donec pulvinar dis massa sapien molestie, a quis sodales ultrices convallis diam semper ante pellentesque, dignissim nascetur nam interdum ullamcorper laoreet urna tempor. Pharetra leo iaculis facilisi euismod himenaeos per pellentesque platea, malesuada lobortis suscipit egestas tempus sodales odio.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "A vel primis parturient ridiculus felis pretium mi donec tellus mus natoque, cras odio id sem quisque nibh quam scelerisque lectus dignissim nunc, ad erat consequat egestas ut justo etiam per proin semper. Orci litora pulvinar auctor luctus velit nulla convallis nisl sem hac scelerisque, viverra a nisi eget arcu aenean vulputate porta venenatis praesent gravida elementum, suspendisse nibh natoque rutrum feugiat at sollicitudin augue fusce suscipit. Luctus tempus senectus sodales risus aliquam ultricies arcu ac, auctor aptent pretium velit nibh pellentesque donec inceptos, lectus morbi netus sem posuere varius odio.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Ut mauris nulla risus curae rutrum luctus auctor velit, platea taciti placerat arcu posuere montes ridiculus primis, ullamcorper donec facilisis mi vel suspendisse blandit. Bibendum lectus eleifend convallis justo quam senectus parturient semper suspendisse phasellus, potenti nibh montes sollicitudin gravida eros ornare elementum aliquam, ridiculus himenaeos aliquet facilisi interdum habitasse ultrices pellentesque ut. Non mus pellentesque suspendisse pulvinar senectus quisque hendrerit nisl luctus sapien himenaeos, turpis ullamcorper nulla ultrices nascetur dictumst condimentum erat phasellus varius et, eleifend inceptos convallis imperdiet posuere habitasse dis facilisi felis lacus. Sem proin velit condimentum mollis tellus hendrerit natoque cum vestibulum, mus libero tortor litora fames praesent habitasse lacinia auctor, aenean eget at commodo cubilia erat vehicula facilisis.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Tellus porttitor facilisis taciti penatibus placerat metus porta imperdiet odio mollis pellentesque, nulla enim urna cubilia morbi ac litora id augue potenti, class et suspendisse egestas conubia maecenas venenatis fames vel viverra. Etiam nisl aliquam torquent molestie praesent convallis est, habitant taciti quisque condimentum lobortis conubia, curabitur quam consequat curae per cum. Ante eget maecenas ornare lobortis aliquet imperdiet turpis, massa elementum purus montes pulvinar torquent est, enim donec tellus luctus consequat fermentum. Non nisi rhoncus sed lacus hac fusce nulla torquent, felis euismod blandit est lacinia faucibus urna vestibulum lobortis, senectus tincidunt cras primis aenean fermentum cursus.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Massa est orci vivamus augue vehicula duis fames netus feugiat ridiculus facilisi tristique viverra himenaeos, per semper fusce ultrices urna commodo felis quis interdum ultricies aptent vulputate. Libero fringilla litora magnis scelerisque mattis sollicitudin dapibus vulputate, metus varius ac nunc massa morbi nascetur faucibus, quis per ullamcorper id porta penatibus platea. Penatibus ut nostra aliquet iaculis nunc facilisi varius tincidunt nisi bibendum arcu, etiam enim pellentesque urna dui euismod sagittis ultricies dapibus himenaeos curabitur rhoncus, dictum potenti massa vulputate hac quis fusce porttitor posuere est.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Venenatis id leo ultrices felis platea eleifend non, imperdiet integer dapibus duis potenti ultricies vulputate, semper vivamus torquent dignissim convallis conubia. Phasellus cursus condimentum magnis senectus curabitur nibh dui class enim imperdiet, urna torquent ultricies venenatis fames lectus augue diam ut, turpis eget fusce varius nisl id ante tellus viverra. Est imperdiet hac lacus sagittis ante ad viverra lectus ultricies vel litora donec egestas, dui pretium condimentum nunc metus vivamus libero varius blandit feugiat vehicula.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "Luctus phasellus blandit iaculis nam id rutrum nibh penatibus, morbi vestibulum proin cursus rhoncus laoreet condimentum sagittis, quam massa dis senectus consequat imperdiet tellus. Morbi consequat metus inceptos ad enim congue at per, elementum pulvinar id et vulputate quisque tellus massa dignissim, luctus interdum quis dapibus in cursus nisi. Sollicitudin senectus et parturient consequat taciti torquent, nostra dignissim semper ullamcorper pellentesque euismod phasellus, dictum hac mus condimentum curabitur.",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "justify",
              indent: 0,
              type: "paragraph",
              version: 1,
              textFormat: 0,
              textStyle: "",
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "root",
          version: 1,
        },
      },
      category: "6927a87651d22936d3955278",
      __v: 0,
    },
  ],
};
