export const SCHOOL_TYPE_LABELS: Record<string, string> = {
  K11: "Sekolah Model Khas Komprehensif 11",
  K9: "Sekolah Model Khas Komprehensif 9",
  KT6: "Kolej Tingkatan Enam",
  KV: "Kolej Vokasional",
  "MODEL KHAS": "Sekolah Model Khas",
  SBJK: "Sekolah Bimbingan Jalinan Kasih",
  SBP: "Sekolah Berasrama Penuh",
  SENI: "Sekolah Seni Malaysia",
  SJKC: "Sekolah Jenis Kebangsaan (Cina)",
  SJKT: "Sekolah Jenis Kebangsaan (Tamil)",
  SK: "Sekolah Kebangsaan",
  "SK KHAS": "Sekolah Kebangsaan Pendidikan Khas",
  "SM KHAS": "Sekolah Menengah Pendidikan Khas",
  "SM SABK": "Sekolah Menengah Agama Bantuan Kerajaan",
  SMK: "Sekolah Menengah Kebangsaan",
  SMKA: "Sekolah Menengah Kebangsaan Agama",
  SMT: "Sekolah Menengah Teknik",
  "SR SABK": "Sekolah Rendah Agama Bantuan Kerajaan",
  SUKAN: "Sekolah Sukan Malaysia",
};

export const SCHOOL_LEVEL: Record<string, string[]> = {
  K11: ["RENDAH", "MENENGAH"],
  K9: ["RENDAH", "MENENGAH"],
  KT6: ["MENENGAH"],
  KV: ["MENENGAH"],
  "MODEL KHAS": ["RENDAH", "MENENGAH"],
  SBJK: ["RENDAH", "MENENGAH"],
  //   SBK: ["RENDAH", "MENENGAH"], not exist in db check on 15/03/26
  SBP: ["MENENGAH"],
  SENI: ["MENENGAH"],
  SJKC: ["RENDAH"],
  SJKT: ["RENDAH"],
  SK: ["RENDAH"],
  "SK KHAS": ["RENDAH"],
  "SM KHAS": ["MENENGAH"],
  "SM SABK": ["MENENGAH"],
  SMK: ["MENENGAH"],
  SMKA: ["MENENGAH"],
  SMT: ["MENENGAH"],
  "SR SABK": ["RENDAH"],
  SUKAN: ["RENDAH", "MENENGAH"],
};
