
export const schoolMarkers = [
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "CHENDERIANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0001",
    namaSekolah: "SEKOLAH KEBANGSAAN TOH TANDEWA SAKTI",
    alamatSurat: "JALAN KELAB",
    poskodSurat: "35000",
    bandarSurat: "TAPAH",
    noTelefon: "054011341",
    noFax: "054010387",
    email: "ABA0001@moe.edu.my",
    lokasi: "Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 510,
    guru: 45,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "ADA",
    lat: 4.196920426,
    lng: 101.2560752,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "AYER KUNING",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0002",
    namaSekolah: "SEKOLAH KEBANGSAAN PENDITA ZA'BA",
    alamatSurat: "JALAN TAPAH ROAD",
    poskodSurat: "35400",
    bandarSurat: "TAPAH ROAD",
    noTelefon: "054182740",
    noFax: "054182740",
    email: "ABA0002@moe.edu.my",
    lokasi: "Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 420,
    guru: 35,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.178275806,
    lng: 101.2006171,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "AYER KUNING",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0003",
    namaSekolah: "SEKOLAH KEBANGSAAN BANIR",
    alamatSurat: "BANIR",
    poskodSurat: "35400",
    bandarSurat: "TAPAH ROAD",
    noTelefon: "01165750521",
    noFax: "TIADA",
    email: "ABA0003@moe.edu.my",
    lokasi: "Bandar",
    gred: "SKM B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 36,
    guru: 12,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.204361,
    lng: 101.181893,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "CHENDERIANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0004",
    namaSekolah: "SEKOLAH KEBANGSAAN TEMOH",
    alamatSurat: "KAMPUNG TEMOH STESEN",
    poskodSurat: "35350",
    bandarSurat: "TEMOH",
    noTelefon: "01165566954",
    noFax: "TIADA",
    email: "ABA0004@moe.edu.my",
    lokasi: "Bandar",
    gred: "B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 115,
    guru: 17,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.235840515,
    lng: 101.1728194,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "CHENDERIANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0005",
    namaSekolah: "SEKOLAH KEBANGSAAN CHENDERIANG",
    alamatSurat: "JALAN CHENDERIANG",
    poskodSurat: "35300",
    bandarSurat: "CHENDERIANG",
    noTelefon: "054030268",
    noFax: "054030268",
    email: "ABA0005@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 168,
    guru: 19,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.26798,
    lng: 101.240556,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TANJONG MALIM",
    dun: "SUNGKAI",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0006",
    namaSekolah: "SEKOLAH KEBANGSAAN BIDOR",
    alamatSurat: "JALAN SUNGKAI",
    poskodSurat: "35500",
    bandarSurat: "BIDOR",
    noTelefon: "054340797",
    noFax: "054340797",
    email: "ABA0006@moe.edu.my",
    lokasi: "Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 288,
    guru: 27,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.107830073,
    lng: 101.2885528,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TANJONG MALIM",
    dun: "BEHRANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0007",
    namaSekolah: "SEKOLAH KEBANGSAAN KAMPONG POH",
    alamatSurat: "KAMPONG POH",
    poskodSurat: "35500",
    bandarSurat: "BIDOR",
    noTelefon: "01165750582",
    noFax: "TIADA",
    email: "ABA0007@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "SKM B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 92,
    guru: 13,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.087714,
    lng: 101.333928,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "CHENDERIANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0008",
    namaSekolah: "SEKOLAH KEBANGSAAN BATU TIGA",
    alamatSurat: "KAMPUNG BATU TIGA",
    poskodSurat: "35350",
    bandarSurat: "TEMOH",
    noTelefon: "054198507",
    noFax: "054190161",
    email: "ABA0008@moe.edu.my",
    lokasi: "Bandar",
    gred: "B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 189,
    guru: 18,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.225044552,
    lng: 101.2275938,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "CHENDERIANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0009",
    namaSekolah: "SEKOLAH KEBANGSAAN BATU MELINTANG",
    alamatSurat: "KAMPUNG BATU MELINTANG",
    poskodSurat: "35000",
    bandarSurat: "TAPAH",
    noTelefon: "054011249",
    noFax: "TIADA",
    email: "ABA0009@moe.edu.my",
    lokasi: "Bandar",
    gred: "SKM B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 129,
    guru: 15,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.199232221,
    lng: 101.2849985,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "AYER KUNING",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0010",
    namaSekolah: "SEKOLAH KEBANGSAAN HAJI HASAN",
    alamatSurat: "CHANGKAT PETAI",
    poskodSurat: "35400",
    bandarSurat: "TAPAH ROAD",
    noTelefon: "056591069",
    noFax: "056591069",
    email: "ABA0010@moe.edu.my",
    lokasi: "Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 268,
    guru: 29,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.126494,
    lng: 101.151,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "CHENDERIANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0011",
    namaSekolah: "SEKOLAH KEBANGSAAN SRI KINJANG",
    alamatSurat: "CHENDERIANG",
    poskodSurat: "35300",
    bandarSurat: "CHENDERIANG",
    noTelefon: "TIADA",
    noFax: "TIADA",
    email: "ABA0011@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 171,
    guru: 16,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.298925082,
    lng: 101.2466694,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "CHENDERIANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0012",
    namaSekolah: "SEKOLAH KEBANGSAAN KAMPONG PAHANG",
    alamatSurat: "JALAN PAHANG",
    poskodSurat: "35000",
    bandarSurat: "TAPAH",
    noTelefon: "054010396",
    noFax: "054010396",
    email: "ABA0012@moe.edu.my",
    lokasi: "Bandar",
    gred: "B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 163,
    guru: 18,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.224791585,
    lng: 101.2906353,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "CHENDERIANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0013",
    namaSekolah: "SEKOLAH KEBANGSAAN BATU TUJUH",
    alamatSurat: "JALAN PAHANG",
    poskodSurat: "35000",
    bandarSurat: "TAPAH",
    noTelefon: "054010735",
    noFax: "054010735",
    email: "ABA0013@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 465,
    guru: 40,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.250268,
    lng: 101.318631,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "AYER KUNING",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0014",
    namaSekolah: "SEKOLAH KEBANGSAAN JERAM MENGKUANG",
    alamatSurat: "BATU 5, JERAM MENGKUANG",
    poskodSurat: "35500",
    bandarSurat: "BIDOR",
    noTelefon: "01165566341",
    noFax: "TIADA",
    email: "ABA0014@moe.edu.my",
    lokasi: "Bandar",
    gred: "SKM B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 67,
    guru: 12,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.067267615,
    lng: 101.2414126,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "CHENDERIANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0015",
    namaSekolah: "SEKOLAH KEBANGSAAN SUNGAI LESONG",
    alamatSurat: "KG SUNGAI LESONG",
    poskodSurat: "31950",
    bandarSurat: "MAMBANG DI AWAN",
    noTelefon: "054780468",
    noFax: "054780468",
    email: "ABA0015@moe.edu.my",
    lokasi: "Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 276,
    guru: 29,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.231541228,
    lng: 101.1454794,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "CHENDERIANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0016",
    namaSekolah: "SEKOLAH KEBANGSAAN AYER KUNING",
    alamatSurat: "AIR KUNING KAMPAR",
    poskodSurat: "31920",
    bandarSurat: "KAMPAR",
    noTelefon: "054789326",
    noFax: "054789326",
    email: "ABA0016@moe.edu.my",
    lokasi: "Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 183,
    guru: 23,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "ADA",
    lat: 4.194635174,
    lng: 101.1435608,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "CHENDERIANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0017",
    namaSekolah: "SEKOLAH KEBANGSAAN BATU MASJID",
    alamatSurat: "KAMPONG BATU MASJID",
    poskodSurat: "35350",
    bandarSurat: "TEMOH",
    noTelefon: "054010908",
    noFax: "TIADA",
    email: "ABA0017@moe.edu.my",
    lokasi: "Bandar",
    gred: "SKM B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 69,
    guru: 14,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.226201,
    lng: 101.200528,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TANJONG MALIM",
    dun: "SUNGKAI",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0018",
    namaSekolah: "SEKOLAH KEBANGSAAN SUNGKAI",
    alamatSurat: "SUNGKAI",
    poskodSurat: "35600",
    bandarSurat: "SUNGKAI",
    noTelefon: "054388434",
    noFax: "054388434",
    email: "ABA0018@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 509,
    guru: 45,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "ADA",
    lat: 3.995430141,
    lng: 101.3097114,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TANJONG MALIM",
    dun: "BEHRANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0019",
    namaSekolah: "SEKOLAH KEBANGSAAN PERLOK",
    alamatSurat: "JALAN MENDERANG",
    poskodSurat: "35600",
    bandarSurat: "SUNGKAI",
    noTelefon: "054386911",
    noFax: "054386911",
    email: "ABA0019@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 159,
    guru: 19,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.010141999,
    lng: 101.342328,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TANJONG MALIM",
    dun: "SUNGKAI",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0020",
    namaSekolah: "SEKOLAH KEBANGSAAN BIKAM",
    alamatSurat: "KAMPUNG BIKAM",
    poskodSurat: "35600",
    bandarSurat: "SUNGKAI",
    noTelefon: "054386179",
    noFax: "054386179",
    email: "ABA0020@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "SKM B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 81,
    guru: 13,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.044575075,
    lng: 101.2974278,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TANJONG MALIM",
    dun: "SLIM",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0024",
    namaSekolah: "SEKOLAH KEBANGSAAN CHANGKAT SULAIMAN",
    alamatSurat: "KG.CHANGKAT SULAIMAN",
    poskodSurat: "35600",
    bandarSurat: "SUNGKAI",
    noTelefon: "054389843",
    noFax: "054389843",
    email: "ABA0024@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 164,
    guru: 17,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 3.971203177,
    lng: 101.2955891,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TANJONG MALIM",
    dun: "BEHRANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0031",
    namaSekolah: "SEKOLAH KEBANGSAAN FELDA SUNGAI KELAH",
    alamatSurat: "FELDA SUNGAI KELAH",
    poskodSurat: "35600",
    bandarSurat: "SUNGKAI",
    noTelefon: "054388500",
    noFax: "054388501",
    email: "ABA0031@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 142,
    guru: 19,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 3.989146238,
    lng: 101.3698264,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "CHENDERIANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0034",
    namaSekolah: "SEKOLAH KEBANGSAAN BATU 14",
    alamatSurat: "JALAN PAHANG",
    poskodSurat: "35000",
    bandarSurat: "TAPAH",
    noTelefon: "TIADA",
    noFax: "TIADA",
    email: "ABA0034@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 291,
    guru: 26,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.322611236,
    lng: 101.3273251,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TANJONG MALIM",
    dun: "SLIM",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0035",
    namaSekolah: "SEKOLAH KEBANGSAAN BESOUT 3",
    alamatSurat: "FELDA GUNUNG BESOUT 3",
    poskodSurat: "35600",
    bandarSurat: "SUNGKAI",
    noTelefon: "054312313",
    noFax: "054312313",
    email: "ABA0035@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 275,
    guru: 28,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 3.843797295,
    lng: 101.3003989,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TANJONG MALIM",
    dun: "SLIM",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0110",
    namaSekolah: "SEKOLAH KEBANGSAAN TROLAK UTARA",
    alamatSurat: "FELDA TROLAK UTARA",
    poskodSurat: "35600",
    bandarSurat: "SUNGKAI",
    noTelefon: "054323189",
    noFax: "054321004",
    email: "ABA0110@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 338,
    guru: 30,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 3.950507367,
    lng: 101.3585782,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TANJONG MALIM",
    dun: "SLIM",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0118",
    namaSekolah: "SEKOLAH KEBANGSAAN TROLAK SELATAN",
    alamatSurat: "FELDA TROLAK SELATAN",
    poskodSurat: "35600",
    bandarSurat: "SUNGKAI",
    noTelefon: "054323534",
    noFax: "054322734",
    email: "ABA0118@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 327,
    guru: 33,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "ADA",
    lat: 3.919545422,
    lng: 101.3867882,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TANJONG MALIM",
    dun: "SLIM",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0120",
    namaSekolah: "SEKOLAH KEBANGSAAN SERI BESOUT",
    alamatSurat: "FELDA GUNUNG BESOUT 01",
    poskodSurat: "35600",
    bandarSurat: "SUNGKAI",
    noTelefon: "054311819",
    noFax: "054311819",
    email: "ABA0120@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 455,
    guru: 43,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "ADA",
    lat: 3.847763,
    lng: 101.286544,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TANJONG MALIM",
    dun: "SUNGKAI",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0125",
    namaSekolah: "SEKOLAH KEBANGSAAN POS GEDONG",
    alamatSurat: "PETI SURAT 20",
    poskodSurat: "35500",
    bandarSurat: "BIDOR",
    noTelefon: "TIADA",
    noFax: "TIADA",
    email: "ABA0125@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "SKM B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 75,
    guru: 11,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.170615,
    lng: 101.376862,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TANJONG MALIM",
    dun: "SUNGKAI",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0126",
    namaSekolah: "SEKOLAH KEBANGSAAN KAMPUNG SENTA",
    alamatSurat: "PETI SURAT 20",
    poskodSurat: "35500",
    bandarSurat: "BIDOR",
    noTelefon: "TIADA",
    noFax: "TIADA",
    email: "ABA0126@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "SKM B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 79,
    guru: 12,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.153609,
    lng: 101.330783,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "CHENDERIANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0127",
    namaSekolah: "SEKOLAH KEBANGSAAN POS MUSUH LZ",
    alamatSurat: "PETI SURAT 51",
    poskodSurat: "35000",
    bandarSurat: "TAPAH",
    noTelefon: "TIADA",
    noFax: "TIADA",
    email: "ABA0127@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "SKM B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 52,
    guru: 12,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.264513896,
    lng: 101.4032176,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TANJONG MALIM",
    dun: "BEHRANG",
    peringkat: "Rendah",
    jenisLabel: "K9",
    kodSekolah: "ABA0128",
    namaSekolah: "SEKOLAH KEBANGSAAN JERNANG",
    alamatSurat: "RPS JERNANG",
    poskodSurat: "35600",
    bandarSurat: "SUNGKAI",
    noTelefon: "TIADA",
    noFax: "TIADA",
    email: "ABA0128@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 227,
    guru: 24,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.051292,
    lng: 101.419363,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "CHENDERIANG",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0129",
    namaSekolah: "SEKOLAH KEBANGSAAN TAPAH",
    alamatSurat: "JALAN BIDOR LAMA",
    poskodSurat: "35000",
    bandarSurat: "TAPAH",
    noTelefon: "054016122",
    noFax: "054016122",
    email: "ABA0129@moe.edu.my",
    lokasi: "Bandar",
    gred: "B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 123,
    guru: 17,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.181687397,
    lng: 101.2680084,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD BATANG PADANG",
    parlimen: "TAPAH",
    dun: "AYER KUNING",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA0130",
    namaSekolah: "SEKOLAH KEBANGSAAN BIDOR 2",
    alamatSurat: "JALAN TELUK INTAN",
    poskodSurat: "35500",
    bandarSurat: "BIDOR",
    noTelefon: "054341216",
    noFax: "054340926",
    email: "ABA0130@moe.edu.my",
    lokasi: "Bandar",
    gred: "B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 593,
    guru: 53,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "ADA",
    lat: 4.117048112,
    lng: 101.2769547,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD MANJUNG",
    parlimen: "BERUAS",
    dun: "PENGKALAN BAHARU",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA1001",
    namaSekolah: "SEKOLAH KEBANGSAAN DENDANG",
    alamatSurat: "KAMPUNG DENDANG",
    poskodSurat: "32700",
    bandarSurat: "BERUAS",
    noTelefon: "01165750536",
    noFax: "01165750536",
    email: "ABA1001@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 89,
    guru: 15,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.502661886,
    lng: 100.8154582,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD MANJUNG",
    parlimen: "BERUAS",
    dun: "PENGKALAN BAHARU",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA1002",
    namaSekolah: "SEKOLAH KEBANGSAAN BERUAS",
    alamatSurat: "JALAN PARIT",
    poskodSurat: "32700",
    bandarSurat: "BERUAS",
    noTelefon: "056740696",
    noFax: "056749009",
    email: "ABA1002@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 230,
    guru: 30,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.498995,
    lng: 100.786063,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD MANJUNG",
    parlimen: "BERUAS",
    dun: "PENGKALAN BAHARU",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA1003",
    namaSekolah: "SEKOLAH KEBANGSAAN KAMPUNG KOTA",
    alamatSurat: "JALAN SITIAWAN",
    poskodSurat: "32700",
    bandarSurat: "BERUAS",
    noTelefon: "056748048",
    noFax: "056748048",
    email: "ABA1003@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 111,
    guru: 17,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.479139195,
    lng: 100.7844878,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD MANJUNG",
    parlimen: "BERUAS",
    dun: "PENGKALAN BAHARU",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA1004",
    namaSekolah: "SEKOLAH KEBANGSAAN GELONG GAJAH",
    alamatSurat: "KAMPUNG KEDAH",
    poskodSurat: "32700",
    bandarSurat: "BERUAS",
    noTelefon: "056721145",
    noFax: "056721145",
    email: "ABA1004@moe.edu.my",
    lokasi: "Luar Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 260,
    guru: 29,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "ADA",
    lat: 4.411288575,
    lng: 100.7784159,
    skm_150: false,
  },
  {
    negeri: "PERAK",
    ppd: "PPD MANJUNG",
    parlimen: "BERUAS",
    dun: "PENGKALAN BAHARU",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA1005",
    namaSekolah: "SEKOLAH KEBANGSAAN CHANGKAT CHERMIN",
    alamatSurat: "CHANGKAT CHERMIN",
    poskodSurat: "32400",
    bandarSurat: "AYER TAWAR",
    noTelefon: "053765253",
    noFax: "053765253",
    email: "ABA1005@moe.edu.my",
    lokasi: "Bandar",
    gred: "B",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 115,
    guru: 16,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "TIADA",
    lat: 4.348482,
    lng: 100.817463,
    skm_150: true,
  },
  {
    negeri: "PERAK",
    ppd: "PPD MANJUNG",
    parlimen: "BERUAS",
    dun: "PENGKALAN BAHARU",
    peringkat: "Rendah",
    jenisLabel: "SK",
    kodSekolah: "ABA1006",
    namaSekolah: "SEKOLAH KEBANGSAAN AYER TAWAR",
    alamatSurat: "JALAN AYER TAWAR PANTAI REMIS",
    poskodSurat: "32400",
    bandarSurat: "AYER TAWAR",
    noTelefon: "056724248",
    noFax: "056724248",
    email: "ABA1006@moe.edu.my",
    lokasi: "Bandar",
    gred: "A",
    bantuan: "SK",
    bilSesi: "1 Sesi",
    sesi: "Pagi Sahaja",
    enrolmen: 336,
    guru: 35,
    prasekolah: "TIADA",
    enrolmenPrasekolah: 0,
    integrasi: "ADA",
    lat: 4.322562454,
    lng: 100.7730772,
    skm_150: false,
  },
];